### ISSUE TITLE
Consider separating the USB code and the Flash code to make a generic CDC module

### ISSUE THREAD

**Issue by TomKeddie** [tinyfpga/TinyFPGA-Bootloader#10]
Luke, the bootloader is a fabulous concept but the CDC portion has much wider applicability.  It would make a great virtual uart peripheral for an HDL cpu for instance.  You've done a great job of modularising the code, perhaps the CDC could be moved to a separate repo and imported into the bootloader as a module.  Once separate the API to the CDC block could be clarified with some doco or perhaps wrapped as a wishbone peripheral?

**Comment by mithro** [comment]
This has been done by other people and this stack superseded by ValentyUSB + Foboot.
