### ISSUE TITLE
win10 enumeration tests fails

### ISSUE THREAD

**Issue by blacktigersoftware** [tinyfpga/TinyFPGA-Bootloader#26]
This test fails.  May not be a big thing, but I'm having trouble getting a build to work and I found one compiler error in the source, (something trivial, but still).  

make[1]: Entering directory '/home/kend/tinytests/TinyFPGA-Bootloader/tests/win10_enumeration_test'
iverilog -I.. -s top_tb -o test -c ../file_list.txt
./test
VCD info: dumpfile test.vcd opened for output.
          1285581184 ERROR (top_tb.expect_usb_data): data mismatch. usb_tx_data != raw_usb_data
    actual:   0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000f67401000000000061301d5020000002020001124b
    expected: 0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000b8a40100000000002100120920000002020001124b
LOCATION: test.v:         26
    test.v:         33
    test.v:         38
          2604826816 ERROR (top_tb.expect_usb_data): data mismatch. usb_tx_data != raw_usb_data
    actual:   0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000f67401000000000061301d5020000002020001124b
    expected: 0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000b8a40100000000002100120920000002020001124b
    test.v:         58
    test.v:         92
    test.v:        109
          2767066432 ERROR (top_tb.expect_usb_data): data mismatch. usb_tx_data != raw_usb_data
    actual:   0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000f67401000000000061301d5020000002020001124b
    expected: 0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000b8a40100000000002100120920000002020001124b
    test.v:        130
    test.v:        148
    test.v:        181
    test.v:        215
    test.v:        220
    test.v:        222
    test.v:        225
    test.v:        229
    test.v:        231
    test.v:        235
    test.v:        253
    test.v:        265
    test.v:        283
make[1]: Leaving directory '/home/kend/tinytests/TinyFPGA-Bootloader/tests/win10_enumeration_test'

**Comment by terrillmoore** [comment]
Oops, sorry, my #32 is a dup of this. Pull request #33 fixes this for me. This is a bug in the test fixture, no tin the RTL.
