### ISSUE TITLE
"TypeError: ord() expected string of length 1, but int found" - python3 (TinyFPGA BX, Ubuntu 19.04)

### ISSUE THREAD

**Issue by zrecore** [tinyfpga/TinyFPGA-Bootloader#48]
https://github.com/tinyfpga/TinyFPGA-Bootloader/blob/99f87a5947fada082cc11606a2b3370f50e1f970/programmer/tinyprog/__init__.py#L38

... Removing the call to ord() here allows the script to continue execution.

**Comment by mithro** [comment]
@zrecore Can you please test this fixed your issue?

**Comment by zrecore** [comment]
@mithro ok, testing now

**Comment by zrecore** [comment]
Ok, no more python errors using `mithro/TinyFPGA-Bootloader` repo, `master` branch. 👍
(Still getting the gateware size issue, but that's probably a different problem)

<img width="1115" alt="Screen Shot 2019-05-14 at 5 17 13 PM" src="https://user-images.githubusercontent.com/428908/57740388-7a2fa880-766c-11e9-8559-a0946a1c2dc4.png">

**Comment by mithro** [comment]
@zrecore It looks like your still failing? Can you log a full bug for that somewhere (maybe on https://github.com/timvideos/litex-buildenv/issues)?

**Comment by zrecore** [comment]
@mithro added issue at https://github.com/timvideos/litex-buildenv/issues/137
