### ISSUE TITLE
Invalid license

### ISSUE THREAD

**Issue by FFY00** [tinyfpga/TinyFPGA-Bootloader#65]
I am not a laywer and don't know the implications in court but this should probably be fixed:

https://github.com/tinyfpga/TinyFPGA-Bootloader/blob/97f6353540bf7c0d27f5612f202b48f41da75299/LICENSE#L190

**Comment by mithro** [comment]
This is the correct way to apply the license see http://www.apache.org/dev/apply-license.html and https://opensource.google/docs/releasing/preparing/#Apache-header
