### ISSUE TITLE
Latch inferred by yosys

### ISSUE THREAD

**Issue by smunaut** [tinyfpga/TinyFPGA-Bootloader#8]
Some of the 'always' block don't always set every 'reg' and this gets inferred as latch. For instance, for state machine, adding a default assignment of the 'next' state to the 'current' state at the beginning or things like that.

See the attached diff (as .txt because of stupid github ...)

They're all fairly straightforward except _out_ep_acked_  for this one it's a bit of a guess and should be checked by someone who knows the code :p

[tinyfpga.txt](https://github.com/tinyfpga/TinyFPGA-Bootloader/files/2021966/tinyfpga.txt)

**Comment by mithro** [comment]
@smunaut Was this merged into the code at all?

**Comment by smunaut** [comment]
Yup
